Repository redhat-developer/vscode-openshift-tools, pull requests merged in 2023-06, with the labels that each got.

#2944 Update .gitignore
  .gitignore
Labels: review

#2973 Remove dependency on "request"
  package-lock.json
  package.json
  src/webview/welcome/welcomeViewLoader.ts
Labels: dependencies

#2972 Fix code scanning issue 7
  src/webview/devfile-registry/app/home.tsx
Labels: kind/bug
