Repository redhat-developer/vscode-openshift-tools, pull requests merged in 2023-11, with the labels that each got.

#3521 Add OK/Cancel buttons to the text input fields
  src/openshift/cluster.ts
  src/openshift/openshiftItem.ts
  src/registriesView.ts
  src/util/inputValue.ts
Labels: kind/enhancement

#3571 [build] GitHub Action to update the version of oc bundled with the ex…
  .github/workflows/check-oc.yml
  src/tools.json
Labels: component/build

#3592 [build] GitHub Action to update the version of helm bundled with the …
  .github/workflows/check-helm.yml
  src/tools.json
Labels: component/build

#3596 [build] Add arm64 odo binaries into the build
  .github/workflows/check-odo.yml
  src/tools.json
Labels: component/build

#3597 [build] Add arm64 oc binaries into the build
  .github/workflows/check-oc.yml
  src/tools.json
Labels: component/build

#3599 Adding create component from local codebase UI test
  test/ui/common/ui/webview/newComponentWebViewEditor.ts
  test/ui/suite/createComponent.ts
Labels: component/ui-test
