Repository redhat-developer/vscode-openshift-tools, pull requests merged in 2023-09, with the labels that each got.

#3155 [build] Enable GitHub dependabot for NPM dependencies
  .github/dependabot.yml
Labels: component/build

#3201 Remove 'style-loader' dependency as unused
  package-lock.json
  package.json
Labels: dependencies

#3199 Remove ts-loader as a direct dependency
  package-lock.json
  package.json
Labels: dependencies

#3269 [build] Install extension dependencies defined in package.json
  build/install-vscode.ts
Labels: kind/enhancement

#3270 Extension wouldn't start due to missing shelljs
  package-lock.json
  package.json
Labels: priority/blocker, kind/bug
