Repository redhat-developer/vscode-openshift-tools, pull requests merged in 2023-08, with the labels that each got.

#3109 Improve contributing documentation
  CONTRIBUTING.md
Labels: component/documentation

#3118 Updated CONTRIBUTING docs with info on microshift and k3s
  CONTRIBUTING.md
Labels: component/documentation

#3125 [test] Add integration test suite and test for running a component co…
  test/integration/command.test.ts
Labels: component/integration-test

#3133 Background colour for "Create Function" wizard should respect theme.
  src/webview/serverless-function/app/createFunction.tsx
Labels: kind/bug

#3140 [test] A test suite and test for verifying a component command tree
  src/componentsView.ts
  test/unit/openshift/component.test.ts
Labels: component/unit-test
